version: "3.9"
services:

  server:
    image: franrobles8/eoloplants_server
    ports:
      - 3000:3000
    env_file:
      - ./config/prod/.env.server
    depends_on:
      - eoloplantsDB
      - rabbitQueue
    command: >
      bash -c "./wait-for-it.sh eoloplantsDB:3306 --timeout=0 
      && ./wait-for-it.sh rabbitQueue:5672 --timeout=0 -- node src/server.js"
  
  eoloplantsDB:
    image: mysql:8.0.23
    env_file:
      - ./config/prod/.env.eoloplantsdb
    ports:
      - 3306:3306
    volumes:
      - ./data/eoloplantsDB:/data/eoloplantsDB

  rabbitQueue:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672

  weatherService:
    image: franrobles8/eoloplants_weatherservice
    env_file:
      - ./config/prod/.env.weatherservice
    ports:
      - 9090:9090

  plannerService:
    image: franrobles8/eoloplants_planner
    env_file:
      - ./config/prod/.env.planner
    ports:
      - 8081:8081
    depends_on: 
      - rabbitQueue
      - topoService
      - weatherService

  topoDB:
    image: mongo:4.4
    ports:
      - 27017:27017
    volumes:
      - ./data/topoDB:/data/topoDB

  topoService:
    image: franrobles8/eoloplants_toposervice
    env_file:
      - ./config/prod/.env.toposervice
    ports:
      - 8080:8080
    depends_on: 
      - topoDB
